### ISSUE TITLE
ia-vscode extension for Intellij IDEA

### ISSUE THREAD

**Issue by FZDNSZYT** [ItemsAdder/ia-vscode#10]
Maybe you can try to make an idea plug-in, the ecological environment of idea is better than that of vs, personally

**Comment by LoneDev6** [comment]
Depends.
If IDEA allows me to add custom icons near text I could code an extension, but last time I checked it wasn't possible.

Anyway vscode is used by more people and it's easier to install and use than IDEA, most people use it to edit configurations.
