### ISSUE TITLE
Tooltips for whitelist and blacklist are the same

### ISSUE THREAD

**Issue by ShizuArt** [ItemsAdder/ia-vscode#11]
Descriptions for whitelist and blacklist are identical 

![image](https://github.com/ItemsAdder/ia-vscode/assets/98397139/4e19c8bf-7982-48fd-a2f3-df09eeadc7df)

![image](https://github.com/ItemsAdder/ia-vscode/assets/98397139/26c00b14-ac8e-4a30-8520-4615da464b35)

This applies to all uses of blacklist, like break_tools_blacklist etc

**Comment by LoneDev6** [comment]
Thanks, this will be fixed
